CREATE TABLE login_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    username VARCHAR2(50) NOT NULL,        
    ip_address VARCHAR2(45) NOT NULL,      
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    success TINYINT(1) NOT NULL           
);